# Generated by Django 6.0 on 2026-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_consulta_data_hora_remove_consulta_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacoes_paciente',
            field=models.TextField(blank=True, verbose_name='Motivo da visita'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prontuario_medico',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações médicas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REJEITADA', 'Rejeitada'), ('AGENDADA', 'Agendada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10),
        ),
    ]
