# Generated by Django 6.0.1 on 2026-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelamento/Rejeição'),
        ),
    ]
